### ISSUE TITLE
Intended CUDA version constraint?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cusparselt-feedstock#55]
Since conda-forge started building against only the latest CUDA 11 & 12 versions, this means the `{{ compiler("cuda") }}` package constrains `cusparselt` to install only with the latest CUDA versions (and no older ones)

https://github.com/conda-forge/cusparselt-feedstock/blob/a8ce21ebdfb8e102e783cb9b8f13e84307760ba9/recipe/meta.yaml#L38

Is that what we want?

Or do we want more flexibility amongst CUDA versions users can install with? IOW would any CUDA 11 or 12 version be ok? If so, we could make the following additions

```yaml
...

build:
  ...
  ignore_run_exports_from:
    - {{ compiler("cuda") }}

...

requirements:
  ...
  run:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    ...
```

This would allow any CUDA 12 version to be used. We could of course pick options between the two as needed
